language: java
sudo: false
arch:
  - amd64
  - ppc64le
jdk:
  - openjdk8

services:
  - couchdb

before_install:
  - export TERM=dumb
  - while [ $? -ne 0 ]; do sleep 1 && curl -v http://localhost:5984; done
